# Generated by Django 5.2 on 2025-05-15 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand_ariza', '0002_alter_ariza_talaba_alter_natija_talaba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ariza',
            old_name='talaba',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='natija',
            old_name='talaba',
            new_name='user',
        ),
        migrations.AddField(
            model_name='ariza',
            name='ariza_role',
            field=models.CharField(choices=[('oquv', 'oquv'), ('manaviyat', 'manaviyat'), ('ilmiy', 'ilmiy')], default='oquv', max_length=30),
        ),
        migrations.AddField(
            model_name='ariza',
            name='ilmiy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, django.core.validators.MaxValueValidator(100))]),
        ),
        migrations.AddField(
            model_name='ariza',
            name='manaviyat',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, django.core.validators.MaxValueValidator(100))]),
        ),
        migrations.AddField(
            model_name='ariza',
            name='oquv',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, django.core.validators.MaxValueValidator(100))]),
        ),
        migrations.AddField(
            model_name='ariza',
            name='rad_etish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ariza',
            name='tasdiqlash',
            field=models.BooleanField(default=False),
        ),
    ]
