# Generated by Django 5.2.1 on 2025-05-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand_ariza', '0003_rename_talaba_ariza_user_rename_talaba_natija_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
