# Generated by Django 5.2.1 on 2025-05-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand_ariza', '0004_ariza_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='ariza_role',
            field=models.CharField(choices=[('oquv', 'oquv'), ('manaviyat', 'manaviyat'), ('ilmiy', 'ilmiy'), ('talaba', 'talaba')], default='oquv', max_length=30),
        ),
    ]
