# Generated by Django 5.2 on 2025-06-09 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand_ariza', '0006_alter_ariza_ariza_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='ilmiy',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, django.core.validators.MaxValueValidator(100))]),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='manaviyat',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, django.core.validators.MaxValueValidator(100))]),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='oquv',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, django.core.validators.MaxValueValidator(100))]),
        ),
    ]
