# Generated by Django 5.2.1 on 2025-05-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bolim',
            field=models.CharField(choices=[('oquv', 'oquv'), ('manaviyat', 'manaviyat'), ('ilmiy', 'ilmiy')], default='oquv', max_length=30),
        ),
    ]
