# Generated by Django 5.2.1 on 2025-05-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_bolim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bolim',
            field=models.CharField(blank=True, choices=[('oquv', 'oquv'), ('manaviyat', 'manaviyat'), ('ilmiy', 'ilmiy')], default='oquv', max_length=30),
        ),
    ]
