# Generated by Django 5.2.1 on 2025-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_bolim'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sharif',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
