# Generated by Django 5.2 on 2025-06-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_sharif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bolim',
            field=models.CharField(blank=True, choices=[('oquv', 'oquv'), ('manaviyat', 'manaviyat'), ('ilmiy', 'ilmiy')], max_length=30),
        ),
    ]
