# Generated by Django 5.2 on 2025-06-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_bolim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gpa',
            field=models.IntegerField(blank=True),
        ),
    ]
