# Generated by Django 5.2 on 2025-06-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gpa',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
